# Continuous Deployment Pipeline
parameters:
- name: environment
  type: string
- name: vmImageName
  type: string
  default: 'windows-latest'
- name: variableGroup
  type: string
- name: sqlServerVar
  type: string
- name: databaseNameVar
  type: string
- name: keyVaultNameVar
  type: string
- name: serviceConnection        # CHANGED: Direct service connection name (not variable)
  type: string
- name: servicePrincipalNameVar  # CHANGED: Variable name for Service Principal
  type: string
- name: tableNameVar             # CHANGED: Variable name for Table Name
  type: string
- name: runMode
  type: string
  default: 'single'
- name: runIntervalMinutes
  type: number
  default: 30
- name: maxIterations
  type: number
  default: 1

jobs:
- deployment: DeployToEnvironment
  displayName: 'Deploy to ${{ parameters.environment }}'
  pool:
    vmImage: ${{ parameters.vmImageName }}
  environment: ${{ parameters.environment }}
  variables:
  - group: ${{ parameters.variableGroup }}
  strategy:
    runOnce:
      deploy:
        steps:
        # 🔍 DEBUG: Show all parameter values
        - task: PowerShell@2
          displayName: '🔍 DEBUG: Show All Parameter Values'
          inputs:
            targetType: 'inline'
            script: |
              Write-Host "=" * 80 -ForegroundColor Cyan
              Write-Host "🔍 FINAL PARAMETER VALUES" -ForegroundColor Green
              Write-Host "=" * 80 -ForegroundColor Cyan
              
              Write-Host "📝 DIRECT PARAMETERS:" -ForegroundColor Yellow
              Write-Host "  environment:           '${{ parameters.environment }}'" -ForegroundColor White
              Write-Host "  vmImageName:           '${{ parameters.vmImageName }}'" -ForegroundColor White
              Write-Host "  variableGroup:         '${{ parameters.variableGroup }}'" -ForegroundColor White
              Write-Host "  serviceConnection:     '${{ parameters.serviceConnection }}'" -ForegroundColor White
              Write-Host "  runMode:               '${{ parameters.runMode }}'" -ForegroundColor White
              Write-Host "  runIntervalMinutes:    ${{ parameters.runIntervalMinutes }}" -ForegroundColor White
              Write-Host "  maxIterations:         ${{ parameters.maxIterations }}" -ForegroundColor White
              
              Write-Host "" -ForegroundColor White
              Write-Host "🔑 VARIABLE GROUP RESOLUTION:" -ForegroundColor Yellow
              Write-Host "  Variable Group: '${{ parameters.variableGroup }}'" -ForegroundColor White
              Write-Host "  ${{ parameters.sqlServerVar }}:              '$($env:DEV_SQL_SERVER)'" -ForegroundColor Green
              Write-Host "  ${{ parameters.databaseNameVar }}:         '$($env:DEV_DATABASE_NAME)'" -ForegroundColor Green
              Write-Host "  ${{ parameters.keyVaultNameVar }}:         '$($env:DEV_KEY_VAULT_NAME)'" -ForegroundColor Green
              Write-Host "  ${{ parameters.servicePrincipalNameVar }}: '$($env:SERVICE_PRINCIPAL_NAME)'" -ForegroundColor Green
              Write-Host "  ${{ parameters.tableNameVar }}:            '$($env:TABLE_NAME)'" -ForegroundColor Green
              
              Write-Host "" -ForegroundColor White
              Write-Host "🚀 FINAL VALUES FOR DEPLOY-STEPS:" -ForegroundColor Yellow
              Write-Host "  sqlServer:             '$($env:DEV_SQL_SERVER)'" -ForegroundColor Cyan
              Write-Host "  databaseName:          '$($env:DEV_DATABASE_NAME)'" -ForegroundColor Cyan
              Write-Host "  keyVaultName:          '$($env:DEV_KEY_VAULT_NAME)'" -ForegroundColor Cyan
              Write-Host "  servicePrincipalName:  '$($env:SERVICE_PRINCIPAL_NAME)'" -ForegroundColor Cyan
              Write-Host "  tableName:             '$($env:TABLE_NAME)'" -ForegroundColor Cyan
              Write-Host "  serviceConnection:     '${{ parameters.serviceConnection }}'" -ForegroundColor Cyan
              
              Write-Host "=" * 80 -ForegroundColor Cyan
        
        # Use deployment template
        - template: templates/deploy-steps.yml
          parameters:
            environment: ${{ parameters.environment }}
            sqlServer: $(variables['${{ parameters.sqlServerVar }}'])               # FROM Variable Group
            databaseName: $(variables['${{ parameters.databaseNameVar }}'])         # FROM Variable Group
            keyVaultName: $(variables['${{ parameters.keyVaultNameVar }}'])         # FROM Variable Group
            serviceConnection: ${{ parameters.serviceConnection }}                  # DIRECT value (Service Connections can't use variables)
            servicePrincipalName: $(variables['${{ parameters.servicePrincipalNameVar }}'])  # FROM Variable Group
            tableName: $(variables['${{ parameters.tableNameVar }}'])              # FROM Variable Group
            runMode: ${{ parameters.runMode }}
            runIntervalMinutes: ${{ parameters.runIntervalMinutes }}
            maxIterations: ${{ parameters.maxIterations }}
